package enchantHaxe;

import enchant.*;

/**
 * ...
 * @author gaya_K
 */

enum EventType
{
    LOAD;
    PROGRESS;
    ENTER_FRAME;
    EXIT_FRAME;
    ENTER;
    EXIT;
    CHILD_ADDED;
    ADDED;
    ADDED_TO_SCENE;
    CHILD_REMOVED;
    REMOVED;
    REMOVED_FROM_SCENE;
    TOUCH_START;
    TOUCH_MOVE;
    TOUCH_END;
    RENDER;
    INPUT_START;
    INPUT_CHANGE;
    INPUT_END;
    LEFT_BUTTON_DOWN;
    LEFT_BUTTON_UP;
    RIGHT_BUTTON_DOWN;
    RIGHT_BUTTON_UP;
    UP_BUTTON_DOWN;
    UP_BUTTON_UP;
    DOWN_BUTTON_DOWN;
    DOWN_BUTTON_UP;
    A_BUTTON_DOWN;
    A_BUTTON_UP;
    B_BUTTON_DOWN;
    B_BUTTON_UP;
    ADDED_TO_TIMELINE;
    REMOVED_FROM_TIMELINE;
    ACTION_START;
    ACTION_END;
    ACTION_TICK;
    ACTION_ADDED;
    ACTION_REMOVED;
}
